name: Rebuild Wiki

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: '${{ github.repository }}.wiki'
          path: 'wiki'

      - uses: actions/checkout@v4
        with:
          path: 'repo'

      - name: Install Luvit
        run: curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh

      - name: Generating wiki pages
        run: |
          cd repo
          ../luvit docgen.lua

      - name: Updating wiki repo
        run: |
          mv -f $GITHUB_WORKSPACE/repo/docs/* $GITHUB_WORKSPACE/wiki/
          cd $GITHUB_WORKSPACE/wiki
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Rebuild for commit ${{GITHUB_SHA}}"
          git push
