name: Rebuild Wiki

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: '${{ github.repository }}.wiki'
          path: 'wiki'

      - uses: actions/checkout@v4
        with:
          path: 'repo'

      - name: Install Luvit
        run: curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh

      - name: Generate the wiki pages
        run: |
          cd repo
          ../luvit docgen.lua

      - name: Set up bot
        run: |
          mv -f $GITHUB_WORKSPACE/repo/docs/* $GITHUB_WORKSPACE/wiki/
          cd $GITHUB_WORKSPACE/wiki
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update the wiki repo
        run: |
          cd $GITHUB_WORKSPACE/wiki
          git add --all
          git commit -m "Rebuild for commit ${{ github.event.after }}"
          git push
        continue-on-error: true
